### ISSUE TITLE
Test failure in pkg build?

### ISSUE THREAD

**Issue by jbclements** [lives-group/peg-parser#1]
It looks like the peg-parser package is failing tests (possibly related to a testing timeout?) on the racket 8.13 release candidate. You can see the fail log here :

https://plt.cs.northwestern.edu/release-pkg-build/server/built/test-fail/peg-parser.txt

Let me know if this doesn't sound right to you, or if there's other information I can provide. I think we're going to go ahead with the 8.13 release, and not wait on this test failure.

**Comment by jbclements** [comment]
There's also discussion of the blockers, here:

https://github.com/racket/racket/issues/4978

**Comment by jbclements** [comment]
Oops, github already flagged this connection.

**Comment by emcardoso** [comment]
Noted. Some experiments were on the test's folder. Those experiments were removed and will be moved to other repository. 

"I think we're going to go ahead with the 8.13 release, and not wait on this test failure."
I agree with you.

**Comment by jbclements** [comment]
Many thanks! I'm going to close this issue.
